<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Detaily Klienta';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Klient</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="tab-client">
<thead class="bg-primary">
   <th><?php echo $this->translate("Meno"); ?></th>
   <th><?php echo $this->translate("Verzia"); ?></th>
   <th><?php echo $this->translate("Autoprune"); ?></th>
   <th><?php echo $this->translate("Fileretention"); ?></th>
   <th><?php echo $this->translate("Jobretention"); ?></th>
   <th><?php echo $this->translate("Akcie"); ?></th>
</thead>
</table>

</div>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Posledné kompletné zálohy</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="tab-backups">
<thead class="bg-primary">
   <th><?php echo $this->translate("Úloha"); ?></th>
   <th><?php echo $this->translate("Čas vytvorenia"); ?></th>
   <th><?php echo $this->translate("Súborový set"); ?></th>
   <th><?php echo $this->translate("Úroveň"); ?></th>
   <th><?php echo $this->translate("Súborov"); ?></th>
   <th><?php echo $this->translate("Veľkosť"); ?></th>
</thead>
</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script>

$(document).ready(function() {

   $('#tab-client').DataTable( {


                "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },


      "ajax": {
         "url": "<?php echo $this->url('client', array('action' => 'getData'), null) . '?data=details&client='.$this->client; ?>",
         "dataSrc": ""
      },
      "columns" : [
         {
            "className": "client-name",
            "data": "name"
         },
         {
            "className": "client-uname",
            "data": "uname"
         },
         {
            "className": "client-autoprune",
            "data": "autoprune"
         },
         {
            "className": "client-fileretention",
            "data": "fileretention"
         },
         {
            "className": "client-jobretention",
            "data": "jobretention"
         },
         {
            "className": "client-actions",
            "data": null
         }
      ],
      "paging":   false,
      "ordering": false,
      "info":     false,
      "pagingType": "full_numbers",
      "stateSave": true,
      "bFilter": false,
      "columnDefs": [
         {
            "targets": 2,
            "data": "autoprune",
            "render": function(data, type, full, meta) {
               if(data == 1) {
                  var a = '<span class="label label-success">enabled</span>';
               }
               else {
                  var a = '<span class="label label-danger">disabled</span>';
               }
               return a;
            }
         },
         {
            "targets": 3,
            "data": "fileretention",
            "render": function(data, type, full, meta) {
               return Math.floor((data % 31536000) / 86400) + " dní";
            }
         },
         {
            "targets": 4,
            "data": "fileretention",
            "render": function(data, type, full, meta) {
               return Math.floor((data % 31536000) / 86400) + " dní";
            }
         },
         {
            "targets": -1,
            "data": "name",
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/restore/index?type=client&client='; ?>'+data.name+'"><button type="button" class="btn btn-default btn-xs" id="btn-1" data-toggle="tooltip" data-placement="top" title="Obnoviť"><span class="glyphicon glyphicon-import"></span></button></a>';
            }
         }
      ]
   } );

   $('#tab-backups').DataTable( {

                "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },


      "ajax": {
         "url": "<?php echo $this->url('client', array('action' => 'getData'), null) . '?data=backups&client='.$this->client; ?>",
         "dataSrc": ""
      },
      "columns" : [
         {
            "className": "backup-jobid",
            "orderable": true,
            "data": "jobid"
         },
         {
            "className": "backup-starttime",
            "orderable": true,
            "data": "starttime"
         },
         {
            "className": "backup-fileset",
            "orderable": true,
            "data": "fileset",
         },
         {
            "className": "backup-level",
            "orderable": true,
            "data": "level",
         },
         {
            "className": "backup-jobfiles",
            "orderable": true,
            "data": "jobfiles",
         },
         {
            "className": "backup-jobbytes",
            "orderable": true,
            "data": "jobbytes"
         }
      ],
      "paging":   true,
      "ordering": true,
      "info":     true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "columnDefs": [
         {
            "targets": 0,
            "data": "jobid",
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/job/details/'; ?>'+data+'">'+data+'</a>';
            }
         },
         {
            "targets": 3,
            "data": "level",
            "render": function(data, type, full, meta) {
               switch(data) {
                  case "I":
                     var level = 'Inkrementálna';
                     break;
                  case "D":
                     var level = 'Rozdielová';
                     break;
                  case "F":
                     var level = 'Plná záloha';
                     break;
                  default:
                     var level = "";
                     break;
               }
               return level;
            }
         },
         {
            "targets": 5,
            "data": "jobbytes",
            "render": function(data, type, full, meta) {
               if(data == 0) return "0.00 B";
               var k = 1000;
               var units = ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB"];
               var i = Math.floor(Math.log(data) / Math.log(k));
               return parseFloat((data / Math.pow(k, i)).toFixed(2)) + " " + units[i];
            }
         }
      ]
   } );

   $('#tab-client tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

} );

</script>
