<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link   https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright   Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author   Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Detaily Úlohy';
$this->headTitle($title);

?>

<!-- Job -->
<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Úloha</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="jobdetails1">

<thead class="bg-primary">
   <th>Úloha</th>
   <th>Názov</th>
   <th>Klient</th>
   <th>Súborový set</th>
   <th>Typ</th>
   <th>Úroveň</th>
   <th>Skupina</th>
</thead>

</table>

<table class="table table-hover" id="jobdetails2">

<thead class="bg-primary">
   <th>Plánovaný štart</th>
   <th>Reálny štart</th>
   <th>Koniec</th>
   <th>Reálny koniec</th>
</thead>

</table>

<table class="table table-hover" id="jobdetails3">

<thead class="bg-primary">
   <th>Súborov</th>
   <th>Veľkosť</th>
   <th>Chýb</th>
   <th>Stav</th>
</thead>

</table>

</div>
</div>
</div>
</div>

<!-- Log -->
<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Správy</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="joblog">

   <thead class="bg-primary">
      <th>Časová značka</th>
      <th>Správa</th>
   </thead>

</table>

</div>
</div>
</div>
</div>


<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script>

$(document).ready(function() {

   var jobdetails1 = $('#jobdetails1').DataTable( {
	   
	      	                   "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
						"sStatus":         "Stav",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },
				
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=details&jobid='.$this->jobid; ?>",
         "dataSrc": ""
      },
      "columns": [
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null }
      ],
      "paging":   false,
      "ordering": false,
      "info":     false,
      "pagingType": "full_numbers",
      "stateSave": true,
      "bFilter": false,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.jobid;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.name;
            }
         },
         {
            "targets": 2,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.client;
            }
         },
         {
            "targets": 3,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.fileset;
            }
         },
         {
            "targets": 4,
            "data": null,
            "render": function(data, type, full, meta) {
               var output;
               switch(data.type) {
                  case 'B':
                      output = 'Záloha';
                      break;
                  case 'M':
                      output = 'Migrácia';
                      break;
                  case 'V':
                      output = 'Overenie';
                      break;
                  case 'R':
                      output = 'Obnova';
                      break;
                  case 'U':
                      output = 'Konsolový progran';
                      break;
                  case 'I':
                      output = 'Interná systémová úloha';
                      break;
                  case 'D':
                      output = 'Administrácia';
                      break;
                  case 'A':
                      output = 'Archív';
                      break;
                  case 'C':
                      output = 'Copy of a job';
                      break;
                  case 'c':
                      output = 'Kópia úlohy';
                      break;
                  case 'g':
                      output = 'Migrácia úlohy';
                      break;
                  case 'S':
                      output = 'Skenovanie';
                      break;
                  default:
                      output = data.type;
                      break;
               }
               return output;
            }
         },
         {
            "targets": 5,
            "data": null,
            "render": function(data, type, full, meta) {
               switch(data.level) {
                  case 'F':
                     return 'Plná záloha';
                  case 'D':
                     return 'Rozdielová';
                  case 'I':
                     return 'Prírastková';
                  default:
                     return data.level;
               }
            }
         },
         {
            "targets": 6,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.poolname;
            }
         },
      ]
   } );

   var jobdetails2 = $('#jobdetails2').DataTable( {
	   
	      	                   "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
						"sStatus":         "Stav",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },
				
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=details&jobid='.$this->jobid; ?>",
         "dataSrc": ""
      },
      "columns": [
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null }
      ],
      "paging":   false,
      "ordering": false,
      "info":     false,
      "pagingType": "full_numbers",
      "stateSave": true,
      "bFilter": false,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.schedtime;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.starttime;
            }
         },
         {
            "targets": 2,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.endtime;
            }
         },
         {
            "targets": 3,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.realendtime;
            }
         }
      ]
   } );

   var jobdetails3 = $('#jobdetails3').DataTable( {
	   
	                   "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },

      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=details&jobid='.$this->jobid; ?>",
         "dataSrc": ""
      },
      "columns": [
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null }
      ],
      "paging":   false,
      "ordering": false,
      "info":     false,
      "pagingType": "full_numbers",
      "stateSave": true,
      "bFilter": false,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.jobfiles;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               if(data.jobbytes == 0) return "0.00 B";
               var k = 1000;
               var units = ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB"];
               var i = Math.floor(Math.log(data.jobbytes) / Math.log(k));
               return parseFloat((data.jobbytes / Math.pow(k, i)).toFixed(2)) + " " + units[i];
            }
         },
         {
            "targets": 2,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.joberrors;
            }
         },
         {
            "targets": 3,
            "data": null,
            "render": function(data, type, full, meta) {

               var output;

               switch(data.jobstatus) {
                  // Non-fatal error
                  case 'e':
                     output = '<span class="label label-danger">Zlyhanie</span>';
                     break;
                  // Terminated with errors
                  case 'E':
                     output = '<span class="label label-danger">Zlyhanie</span>';
                     break;
                  // Fatal error
                  case 'f':
                     output = '<span class="label label-danger">Zlyhanie</span>';
                     break;
                  // Terminated successful
                  case 'T':
                     output = '<span class="label label-success">Hotovo</span>';
                     break;
                  // Running
                  case 'R':
                     output = '<span class="label label-info">Beží</span>';
                     break;
                  // Created no yet running
                  case 'C':
                     output = '<span class="label label-default">V poradí</span>';
                     break;
                  // Blocked
                  case 'B':
                     output = '<span class="label label-warning">Zablokovaná</span>';
                     break;
                  // Verify found differences
                  case 'D':
                     output = '<span class="label label-warning">Overuje nájdené rozdiely</span>';
                     break;
                  // Canceled by user
                  case 'A':
                     output = '<span class="label label-warning">Zrušená</span>';
                     break;
                  // Waiting for client
                  case 'F':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for storage daemon
                  case 'S':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for new media
                  case 'm':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for media mount
                  case 'M':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for storage resource
                  case 's':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for job resource
                  case 'j':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting for client resource
                  case 'c':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting on maximum jobs
                  case 'd':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting on starttime
                  case 't':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // Waiting on higher priority jobs
                  case 'p':
                     output = '<span class="label label-default">Čaká</span>';
                     break;
                  // SD despooling attributes
                  case 'a':
                     output = '<span class="label label-info">SD despooling attributes</span>';
                     break;
                  // Doing batch insert file records
                  case 'i':
                     output = '<span class="label label-info">Vykonávam dávkové vkladanie súborových záznamov</span>';
                     break;
                  // Incomplete
                  case 'I':
                     output = '<span class="label label-primary">Nekompletná</span>';
                     break;
                  // Committing data
                  case 'L':
                     output = '<span class="label label-info">Nahrávam dáta</span>';
                     break;
                  // Terminated with warnings
                  case 'W':
                     output = '<span class="label label-warning">Varovanie</span>';
                     break;
                  // Doing data despooling
                  case 'l':
                     output = '<span class="label label-info">Doing data despooling</span>';
                     break;
                  // Queued waiting for device
                  case 'q':
                     output = '<span class="label label-default">Queued waiting for device</span>';
                     break;
                  // Default
                  default:
                     output = '<span class="label label-primary">' + data.jobStatus + '</span>';
                     break;
               }

               return output;
            }
         }
      ]
   } );

   var joblog = $('#joblog').DataTable( {
	   
	   	                   "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=logs&jobid='.$this->jobid; ?>",
         "dataSrc": ""
      },
      "columns": [
         { "data": null },
         { "data": null }
      ],
      "paging":   true,
      "ordering": true,
      "info":     true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.time;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               var msg = (data.logtext).replace(/\n/g, "<br />");
               if(msg.search("Error") > 0) {
                  return msg.replace(/Error/g, '<span class="bg-danger text-danger">Chyba</span>');
               }
               else if(msg.search("error") > 0) {
                  return msg.replace(/error/g, '<span class="bg-danger text-danger">chyba</span>');
               }
               else if(msg.search("Warning") > 0) {
                  return msg.replace(/Warning/g, '<span class="bg-warning text-warning">Varovanie</span>');
               }
               else {
                  return msg;
               }
            }
         }
      ]
   } );

} );

</script>
