<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Úlohy';
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('Prehľad'); ?></a></li>
   <li class="active"><a href="<?php echo $this->url('job', array('action'=>'run')); ?>"><?php echo $this->translate('Spustiť'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-10">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Spustiť Úlohy</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="backupjobs">
   <thead class="bg-primary">
      <th><?php echo $this->translate("Meno"); ?></th>
      <th><?php echo $this->translate("Akcie"); ?></th>
   </thead>
</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script>

   $('#backupjobs').DataTable( {
	   
	   	                   "language":    {
                        "sEmptyTable":     "Nie sú k dispozícii žiadne dáta",
                        "sInfo":           "Záznam _START_ až _END_ z celkom _TOTAL_",
                        "sInfoEmpty":      "Záznam 0 až 0 z celkom 0 ",
                        "sInfoFiltered":   "(vyfiltrované spomedzi _MAX_ záznamov)",
                        "sInfoPostFix":    "",
                        "sInfoThousands":  ",",
                        "sLengthMenu":     "Zobraz _MENU_ záznamov",
                        "sLoadingRecords": "Načítavam...",
                        "sProcessing":     "Spracúvam...",
                        "sSearch":         "Hľadať:",
						"sStatus":         "Stav",
                        "sZeroRecords":    "Nenašli sa žiadne vyhovujúce záznamy",
                        "oPaginate": {
                                "sFirst":    "Prvá",
                                "sLast":     "Posledná",
                                "sNext":     "Nasledujúca",
                                "sPrevious": "Predchádzajúca"
                        },
                        "oAria": {
                                "sSortAscending":  ": aktivujte na zoradenie stĺpca vzostupne",
                                "sSortDescending": ": aktivujte na zoradenie stĺpca zostupne"
                        }
                },
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=backupjobs'; ?>",
         "dataSrc": ""
      },
      "columns" : [
         {
            "data": null
         },
         {
            "orderable": false,
            "data": null
         }
      ],
      "paging":   true,
      "ordering": true,
      "info":     true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.name;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/job/queue?job='; ?>'+data.name+'"><button type="button" class="btn btn-default btn-xs" id="btn-1" data-toggle="tooltip" data-placement="top" title="Spustiť"><span class="glyphicon glyphicon-play-circle"></span></button></a>';
            }
         }
      ]
   } );

   $('#backupjobs tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

</script>
