<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Detaily záznamu';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-8">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Záznam</h3>
</div>

<div class="panel-body">

   <table class="table table-condensed">
   <tr><th>ID záznamu</th><td><?php echo $this->escapeHtml($media['mediaid']); ?></td></tr>
   <tr><th>Názov záznamu</th><td><font color="#0073BC"><?php echo $this->escapeHtml($media['volumename']); ?></font></td></tr>
   <tr><th>Typ média</th><td><?php echo $this->escapeHtml($media['mediatype']); ?></td></tr>
   <tr><th><font color="#0073BC">ID typu média</font></th><td></td></tr>
   <tr><th>Značka typu</th><td><?php echo $this->escapeHtml($media['labeltype']); ?></td></tr>
   <tr><th>Prvý zápis</th><td><?php echo $this->printDate($media['firstwritten']); ?></td></tr>
   <tr><th>Posledný zápis</th><td><?php echo $this->printDate($media['lastwritten']); ?></td></tr>
   <tr><th>Dátum záznamu</th><td><?php echo $this->printDate($media['labeldate']); ?></td></tr>
   <tr><th>Počet úloh</th><td><?php echo $this->escapeHtml($media['voljobs']); ?></td></tr>
   <tr><th>Počet súborov</th><td><?php echo $this->escapeHtml($media['volfiles']); ?></td></tr>
   <tr><th>Počet blokov</th><td><?php echo $this->escapeHtml($media['volblocks']); ?></td></tr>
   <tr><th>Počet pripojení</th><td><?php echo $this->escapeHtml($media['volmounts']); ?></td></tr>
   <tr><th>Použitá veľkosť</th><td><?php echo $this->printBytes($media['volbytes']); ?></td></tr>
   <tr><th>Počet chýb</th><td><?php echo $this->escapeHtml($media['volerrors']); ?></td></tr>
   <tr><th>Počet zápisov</th><td><?php echo $this->escapeHtml($media['volwrites']); ?></td></tr>
   <tr><th>Veľkosť kapacity (byt)</th><td><?php echo $this->escapeHtml($media['volcapacitybytes']); ?></td></tr>
   <tr><th>Aktuálny stav</th><td><?php echo $this->escapeHtml($media['volstatus']); ?></td></tr>
   <tr><th>Povolené</th><td><?php echo $this->escapeHtml($media['enabled']); ?></td></tr>
   <tr><th>Recyklované</th><td><?php echo $this->escapeHtml($media['recycle']); ?></td></tr>
   <tr><th><font color="#0073BC">Akcia mazania</font></th><td></td></tr>
   <tr><th>Doba retencie/expirácie</th><td><?php echo $this->printExpiration($media['volretention'], $media['lastwritten'], $media['volstatus']); ?></td></tr>
   <tr><th>Doba trvania výkonu</th><td><?php echo $this->escapeHtml($media['voluseduration']); ?></td></tr>
   <tr><th>Maximálny počet úloh</th><td><?php echo $this->escapeHtml($media['maxvoljobs']); ?></td></tr>
   <tr><th>Maximálny počet súborov</th><td><?php echo $this->escapeHtml($media['maxvolfiles']); ?></td></tr>
   <tr><th>Maximálna veľkosť</th><td><?php echo $this->printBytes($media['maxvolbytes']); ?></td></tr>
   <tr><th>V meniči</th><td><?php echo $this->escapeHtml($media['inchanger']); ?></td></tr>
   <tr><th>ID Úložiska</th><td><?php echo $this->escapeHtml($media['storageid']); ?></td></tr>
   <tr><th>ID Zariadenia</th><td><?php echo $this->escapeHtml($media['deviceid']); ?></td></tr>
   <tr><th><font color="#0073BC">Adresácia média</font></th><td></td></tr>
   <tr><th>Volume readtime</th><td></td></tr>
   <tr><th>Volume writetime</th><td></td></tr>
   <tr><th>Posledný súbor</th><td><?php echo $this->escapeHtml($media['endfile']); ?></td></tr>
   <tr><th>Posledný blok</th><td><?php echo $this->escapeHtml($media['endblock']); ?></td></tr>
   <tr><th>ID Lokality</th><td><?php echo $this->escapeHtml($media['locationid']); ?></td></tr>
   <tr><th>Počet recyklácií</th><td><?php echo $this->escapeHtml($media['recyclecount']); ?></td></tr>
   <tr><th>Prvotný zápis</th><td><?php echo $this->escapeHtml($media['initialwrite']); ?></td></tr>
   <tr><th>ID pamate zásobníka</th><td><?php echo $this->escapeHtml($media['scratchpoolid']); ?></td></tr>
   <tr><th>Recyclepool ID</th><td><?php echo $this->escapeHtml($media['recyclepoolid']); ?></td></tr>
   <tr><th>Šifrovací kľúč</th><td></td></tr>
   <tr><th>Poznámka</th><td><?php echo $this->escapeHtml($media['comment']); ?></td></tr>
   </table>

</div>
</div>
</div>
</div>
